# Generated by Django 4.1.2 on 2022-11-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_iuser_anyfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.iuser'),
        ),
    ]
