# Generated by Django 4.1.2 on 2022-11-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_anyfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anyfile',
            name='user',
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.iuser')),
            ],
        ),
        migrations.AddField(
            model_name='anyfile',
            name='user_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.usernote'),
        ),
    ]
