# Generated by Django 4.1.2 on 2022-11-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_anyfile_user_usernote_anyfile_user_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernote',
            old_name='description',
            new_name='note_description',
        ),
        migrations.RenameField(
            model_name='usernote',
            old_name='title',
            new_name='note_title',
        ),
    ]
